### PR TITLE
BIOIN-1594 fix - duplicate positions in multiple signatures now handl…

### PR DESCRIPTION
**Pull request by kenissur**
…ed correctly with drop_duplicates

### CODE REVIEW

**Review by avigailmo — COMMENTED** [review]
you have pre-commit issues:
https://github.com/Ultimagen/ugbio-utils/actions/runs/11719226843/job/32642040919

https://github.com/Ultimagen/ugbio-utils/blob/main/README.md#pre-commit-tools

**Comment by kenissur** [comment]
Fixed, thanks

[cid:3bb8f0d5-c733-405d-b6b7-3ae27fdc5402]<https://www.ultimagenomics.com/>
Itai Rusinek​​​​
Staff Researcher
E:      ***@***.***
ultimagenomics.com<http://www.ultimagenomics.com/>

________________________________

**Comment by kenissur** [comment]
@avigailmo why the version update you pushed? Should we merge it this way?

**Comment by avigailmo** [comment]
> @avigailmo why the version update you pushed? Should we merge it this way?

it's an automation that run on pr created - to have a unique tag for each branch. In your pr it caused conflicts - I'm not sure why - so I resolved them manually.

the release aligns the version - so it's ok to merge like this

**Pull request merged**
