### PR TITLE
Added tests

### PR DESCRIPTION
**Pull request by ilyasoifer**

### CODE REVIEW

**Comment by ilyasoifer** [comment]
@avigailmo - do I need to modify the CLI as well?

**Comment by avigailmo** [comment]
> @avigailmo - do I need to modify the CLI as well?

what do you mean?

**Review by avigailmo — APPROVED** [review]

**Comment by ilyasoifer** [comment]
Should I add the tests folder to the CLI?

**Comment by avigailmo** [comment]
> Should I add the tests folder to the CLI?. It says "ugbio_core has no tests"

there was a change in the CI - I've updated your pr to run against latest master (and added some fixes to make it run core tests)

**Pull request merged**
